name: Frontend Deployment (CD)

# El criterio exige que solo se ejecute al fusionar en main
on:
  push:
    branches: [ main, principal ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Copiar codigo del repositorio
      uses: actions/checkout@v4

    - name: Simular conexion con Vercel API
      run: echo "Conectando de forma segura con los servidores de Vercel..."

    - name: Desplegar aplicacion en produccion
      run: echo "¡Frontend desplegado exitosamente en https://hr-platform-web.vercel.app!"
